### ISSUE TITLE
Use electron for desktop application ?

### ISSUE THREAD

**Issue by kogp112** [norbjd/imgxplain#2]
How about using electron for this app become desktop app?
https://www.electronjs.org/

**Comment by norbjd** [comment]
:+1: Good idea ! I think using electron is better than to have an application hosted on github pages. However, I think that before doing this, we should refactor the code to be able to import libraries directly in JS, and not relying on imported scripts on `index.html` :

https://github.com/norbjd/imgxplain/blob/6d0e49d411781303ccd2f3692530c80dfc336d4a/public/index.html#L13

I'll create an issue for this.

**Comment by norbjd** [comment]
Latest comment have been fixed with #4

**Comment by norbjd** [comment]
Also, electron does not support ES6 :

https://discuss.atom.io/t/does-electron-support-es6/19366/20
https://stackoverflow.com/questions/35374353/es6-syntax-import-electron-require
