### ISSUE TITLE
Add words csv download function or show words which included in sentences

### ISSUE THREAD

**Issue by kogp112** [norbjd/imgxplain#9]

**Comment by norbjd** [comment]
@kogp112 Maybe solved by #10 ?

**Comment by kogp112** [comment]
Yeah...but when i clicked transcript button , any text-area doesn't shown.

**Comment by kogp112** [comment]
Sorry now i recognized how i can show transcript area. It shouldn't push edit button...

**Comment by kogp112** [comment]
Yeah this issue completed by your PR, Thank you!
